version: "3.8"

services:
  rss-email-summarizer:
    build: .
    ports:
      - "5000:5000"
    environment:
      # Email configuration (REPLACE THESE WITH YOUR ACTUAL VALUES)
      - IMAP_HOST=your.imap.server.com # e.g., imap.gmail.com, outlook.office365.com
      - IMAP_PORT=993
      - IMAP_USER=your-email@example.com # Your actual email address
      - IMAP_PASSWORD=your-password # Your actual password or app password

      # Ollama configuration
      - OLLAMA_API_URL=http://ollama:11434/api/generate
      - OLLAMA_MODEL=llama3
      - OLLAMA_TIMEOUT=60
      - CLEAN_THINKING_CONTENT=true # Set to false to disable cleaning for reasoning models

      # Application configuration
      - USER_NAME=Jeremy
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
      - DATA_DIR=/app

      # Optional: Email filtering
      # - EMAIL_WHITELIST=friend@example.com,family@example.com
      # - EMAIL_BLACKLIST=marketing@company.com,noreply@spam.com

    # For data persistence, uncomment the volumes section below
    volumes:
      - ./data:/app # Uncomment for data persistence
    # Alternative: use named volume instead of bind mount
    # - app_data:/app

    depends_on:
      - ollama

    restart: unless-stopped

    # Removed health check to avoid frequent LLM calls
    # Use /status endpoint manually to check health

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

    # Uncomment if you have GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

volumes:
  ollama_data:
  # Uncomment if using named volume for app data
  # app_data:
