version: "3.8"

services:
  rss-email-summarizer:
    build: .
    ports:
      - "5000:5000"
    environment:
      # Email configuration (set these values)
      - IMAP_HOST=your.imap.server.com
      - IMAP_PORT=993
      - IMAP_USER=your-email@example.com
      - IMAP_PASSWORD=your-password

      # Ollama configuration
      - OLLAMA_API_URL=http://ollama:11434/api/generate
      - OLLAMA_MODEL=llama3
      - OLLAMA_TIMEOUT=60

      # Application configuration
      - USER_NAME=Jeremy
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
      - DATA_DIR=/app/data

      # Optional: Email filtering
      # - EMAIL_WHITELIST=friend@example.com,family@example.com
      # - EMAIL_BLACKLIST=marketing@company.com,noreply@spam.com

    volumes:
      - ./data:/app/data

    depends_on:
      - ollama

    restart: unless-stopped

    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import requests; requests.get('http://localhost:5000/status', timeout=5)",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

    # Uncomment if you have GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

volumes:
  ollama_data:
